// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCur5eaQGUNaxdzw62Ounpg3wqVKD2BT54',
    appId: '1:1095982317804:web:03c559dcfcce2b70be65c9',
    messagingSenderId: '1095982317804',
    projectId: 'w-oapp',
    authDomain: 'w-oapp.firebaseapp.com',
    storageBucket: 'w-oapp.firebasestorage.app',
    measurementId: 'G-JJ3DBYXSSP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvIsWiocgotSLIylKcrqvNNwQ4r--IUKw',
    appId: '1:1095982317804:android:c165c6368c2810debe65c9',
    messagingSenderId: '1095982317804',
    projectId: 'w-oapp',
    storageBucket: 'w-oapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkqHgPgmhMrCZq4wCstjNxU7-4R_f3c9o',
    appId: '1:1095982317804:ios:d7f5e68a598fc3f7be65c9',
    messagingSenderId: '1095982317804',
    projectId: 'w-oapp',
    storageBucket: 'w-oapp.firebasestorage.app',
    iosBundleId: 'com.example.wo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkqHgPgmhMrCZq4wCstjNxU7-4R_f3c9o',
    appId: '1:1095982317804:ios:d7f5e68a598fc3f7be65c9',
    messagingSenderId: '1095982317804',
    projectId: 'w-oapp',
    storageBucket: 'w-oapp.firebasestorage.app',
    iosBundleId: 'com.example.wo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCur5eaQGUNaxdzw62Ounpg3wqVKD2BT54',
    appId: '1:1095982317804:web:c30a45251b7176afbe65c9',
    messagingSenderId: '1095982317804',
    projectId: 'w-oapp',
    authDomain: 'w-oapp.firebaseapp.com',
    storageBucket: 'w-oapp.firebasestorage.app',
    measurementId: 'G-VWBEKW9TWC',
  );
}
